### ISSUE TITLE
feedback | peer review 1

### ISSUE THREAD

**Issue by xmavv** [R3VANEK/bazy-danych-2#5]
Na schemacie bazy danych w pliku ```baza.pdf``` widnieje blad tabela ```courses``` jest zle polaczona z tabela ```rides```.

Zastanawiamy sie tez, dlaczego gender przyjmuje wartosc ```true``` lub ```false```, a nie ```"men"``` i ```"women"``` jako string.

Zauwazylismy również sprzecznosc w nazwach, w tabeli ```rides```: 

```departure_id``` - l. poj

```vehicles_id, clients_id``` - l. mn.

Literowka z slowku passengers w tabeli ```vehicles```.

Wydaje nam sie, ze brakuje wartości ```NOT NULL``` w niektorych tabelach.

**Comment by R3VANEK** [comment]
Dzięki za review, poprawiliśmy:
- wartości `NOT NULL` do odpowiednich kolumn w tabelach
- złe połączenie `courses` i `rides`
- literówkę w `passengers`

Jeśli chodzi o kolumnę gender, to przyjmuje wartości typu boolean po prostu żeby oszczędzać miejsce. Zmienienie typu tak jak proponujecie na `VARCHAR` jest słabe z poziomu walidacji dozwolonych wartości + właśnie niepotrzebnego marnowania miejsca. W aplikacji przyjmiemy konwencje, że np. `gender=1` oznaczać będzie kobietę, w przeciwnym wypadku mężczyznę.

Sprzeczność w nazwach jest zamierzona, `departure_id` oraz `destination_id` nie ma nazw w liczbie mnogiej żeby nie sugerować że istnieją tabelę o nazwach `departure` i `destination`. Te klucze obce mają funkcjonalne nazwy które chociaż łączą inną tabelę, to będą ułatwiały czytanie i pisanie kodu niż po prostu `planets_id`
