### ISSUE TITLE
Peer review 1

### ISSUE THREAD

**Issue by gizlu** [R3VANEK/bazy-danych-2#7]
NOTE: Nie znam wszystkich założeń, przez co moje uwagi mogą nie mieć sensu.

![image](https://github.com/user-attachments/assets/8f0ce42f-1bb8-423a-a679-7bc87b74c12d)
Po co na każdym "bilecie" (rides) trzymać id pojazdu? Nie wystarczy trzymać go w opisie kursu? 
Wydaje mi się, że na podstawie id pojazdu można wydedukować id kierowcy. W takiej sytuacji w tabeli `courses` możemy zrezygnować z pola `drivers_id` na rzecz `vehicles_id`.
![384963210-8f0ce42f-1bb8-423a-a679-7bc87b74c12d](https://github.com/user-attachments/assets/e88c0cac-7713-425b-add7-c827e6144a22)

**Comment by R3VANEK** [comment]
oh faktycznie dzięki wielkie. Faktycznie to wydaje się logiczniejsze z perspektywy bazy i zaimplementowaliśmy to
